[package]
name = "day3"
version = "0.1.0"
edition = "2021"

[lib]
name = "day3_solve"
path = "src/lib.rs"

[[bin]]
name = "day3"
path = "src/main.rs"

[dependencies]

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "day3_benchmark"
harness = false
