[package]
name = "day2"
version = "0.1.0"
edition = "2021"

[lib]
name = "day2_solve"
path = "src/lib.rs"

[[bin]]
name = "day2"
path = "src/main.rs"

[dependencies]

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "day2_benchmark"
harness = false
