[package]
name = "day16"
version = "0.1.0"
edition = "2021"

[lib]
name = "day16_solve"
path = "src/lib.rs"

[[bin]]
name = "day16"
path = "src/main.rs"

[dependencies]
pathfinding = "4.1.1"
regex = "1.7.0"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "day16_benchmark"
harness = false
